name: image_hash
description: Caclulate hash of an image.
version: 1.0.0
repository: https://github.com/lollipopkit/image_hash.dart
publish_to: https://pub.dev

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  image: ^4.5.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
