name: image_hash
description: This package allows you to generate hash values from images and compare them to determine similarity, making it useful for tasks like finding duplicate or similar images, image recognition, and content-based image retrieval.
version: 1.0.9
repository: https://github.com/lollipopkit/image_hash.dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  image: ^4.5.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
